PyConGhana/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls import handler404, handler500
from jet.dashboard.dashboard_modules import google_analytics_views

from django_robohash.views import robohash 
from django.views.static import serve 

from django.conf.urls import handler404, handler500

from home import views

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('about/', include('about.urls', namespace='about')),
    path('tickets/', include('tickets.urls', namespace='ticket')),
    path('accounts/', include('registration.backends.default.urls')),
    #path('accounts/', include('registration.backends.simple.urls')),
    path('profile/', include('registration.urls', namespace='profiles')),
    # path('accounts/', include('accounts.urls', namespace='accounts')),
    path('sponsors/', include('sponsors.urls', namespace='sponsors')),
    path('coc/', include('coc.urls', namespace='coc')),
    # path('contact/', include('contact.urls', namespace='contact')),
    path('schedule/', include('schedule.urls', namespace='schedule')),
    path('support_us/', include('support_us.urls', namespace='support_us')),
    path('prospectus/', include('sponsors.urls', namespace='Prospectus')),
    path('talks/', include('talks.urls', namespace='talks')),
    path('privacypolicy/', include('privacypolicy.urls', namespace='privacypolicy')),
    path('newsletter/', include('newsletter.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('faq/', include('faq.urls', namespace='faqs')),
    path('pyconorganizers/', admin.site.urls),
    path('pycons/', include('pycons.urls', namespace='pycons')),
    path('robohash/<string>/', robohash, name='robohash'),
    path('avatar/', include('avatar.urls')),


    #Past PyCons 
    path('2018/', include('pycongh2018.urls', namespace='pycongh2018')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.

handler404 = 'home.views.handler404'




# Modifies default django admin titles and headers with custom app detail.
admin.site.site_header = "PyCon Ghana Admin"
admin.site.site_title = "PyCon Ghana Admin Portal"
admin.site.index_title = "Welcome to PyCon Ghana Portal"

coc/urls.py
from django.urls import path
from . import views

app_name = 'coc'
urlpatterns = [
    path('', views.coc, name='coc')
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', view=views.home, name='home'),
]

registration/urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from .views import UpdateProfileView, ProfileView, UpdateLoginView, CreateProfileView, PasswordView, SuccessView 
from . import views

app_name = 'registration'

urlpatterns = [ 
    path('create_profile/', login_required(CreateProfileView.as_view()), name='create_profile'),
    re_path('update/(?P<pk>\d+)/', login_required(UpdateProfileView.as_view()), name='update'), 
    path('', login_required(ProfileView.as_view()), name='profile_home'),
    re_path('password_change/(?P<pk>\d+)/', login_required(PasswordView.as_view()), name='password_change'),
    re_path('login_details/(?P<pk>\d+)/', login_required(UpdateLoginView.as_view()), name='login_details'),
    path('profile_updated/', login_required(SuccessView.as_view()), name='profile_update'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

talks/urls.py
from rest_framework import routers
from django.urls import include, path, re_path
from talks.views import TalkViewsSets
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from talks import views


app_name = 'talks'
router = routers.DefaultRouter()
router.register(r'talks', TalkViewsSets)

urlpatterns = [
    path('accepted_talks', views.AcceptedTalksView.as_view(), name='accepted_talks'),
    path('submit_talk', login_required(views.submit_talk), name='submit_talk'),
    re_path(r'^edit_talk/(?P<pk>\d+)', login_required(views.TalkView.as_view()), name='edit_talk'),
    path('talk_list', login_required(views.TalkList.as_view()), name='talk_list'),
    re_path(r'^talk_details/(?P<pk>\d+)', views.TalkDetailView.as_view(), name='talk_details'),
    path('submitted', login_required(views.SuccessView.as_view()), name='submitted'),
    path('uploads', views.home, name='home'),
    path('submit', views.submit, name='submit'),
    path('proposing_a_talk', views.proposing, name='proposing'),
    path('recording', views.recording, name='recording'),
    path('uploads_simple', views.simple_upload, name='simple_upload'),
    path('uploads_form', views.model_form_upload, name='model_form_upload'),
    ]

urlpatterns += router.urls

uploads/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from uploads.core import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^uploads/simple/$', views.simple_upload, name='simple_upload'),
    url(r'^uploads/form/$', views.model_form_upload, name='model_form_upload'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
#home views 
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
 



# 2022. 
 
def home(request):
    context = {}
    template = '2022/home.html'
    return render(request, template, context)
 
def handler404(request, exception):
    return render(request, '404.html', locals())

templates/profiles/create_profile.html
{% extends "base22.html" %}
{% load i18n static avatar_tags crispy_forms_tags %}
{% block meta_title %}{% if page %}{{ page.meta_title }}{% else %}{% trans "Create Profile | Pycon Ghana" %}{% endif %}{% endblock %}


{% block content %}

<!-- ========== HEADER ========== -->
{% include '2022/header.html' %}
<!-- ========== END HEADER ========== -->
 
    <!--================ Breadcrumb ================-->
    <div class="mad-breadcrumb">
        <div class="container">
          <h1 class="mad-page-title mad-title-with-line">Create your Profile {% firstof user.get_short_name user.get_username|capfirst %}</h1>
          <nav class="mad-breadcrumb-path"><span><a href="/">Home</a></span>/<span>Profile</span>
          </nav>
        </div>
      </div>
      <!--================ End of Breadcrumb ================-->
      <div class="mad-content">
        <div class="container">
          <div class="row mad-row-size-3">
            <main class="col-xl-9 col-lg-8">
                <section class="speakers" id="speakers">
                    <div class="container">
                    <div class="row">
                        <div class="col-sm-12 col-md-4">
                                <div class="section-title wow fadeInUp">
                                    <h4>   </h4>
                                </div>
                                <div class="panel panel-warning wow fadeInRight">
                                        <div class="panel-body">
                                           <div class="row">
                                                    <div class="col-md-10">
                                                        <ul>
                                                            {% if request.user|has_avatar %} 
                                                                                                            
                                                            <div data-isotope-layout="grid" data-isotope-filter="#portfolio-filter" class="mad-team  mad-grid--isotope">
                                                                <div class="mad-grid-sizer"></div>
                                                                <div class="mad-grid-item mad-category-programming">
                                                                    <!--================ Team Member ================--> 
                                                                    <figure class="mad-team-member">
                                                                    {% avatar user 110 class="img-circle img-responsive" id="user_avatar" %}
                                                                    </figure>
                                                                    <!--================ End Of Team Member ================-->
                                                                </div>
                                                            </div>      
                                                            {% else %} 
                                                            <div data-isotope-layout="grid" data-isotope-filter="#portfolio-filter" class="mad-team  mad-grid--isotope">
                                                                <div class="mad-grid-sizer"></div>
                                                                <div class="mad-grid-item mad-category-programming">
                                                                    <!--================ Team Member ================-->
                                                                    <figure class="mad-team-member">
                                                                    <a class="mad-team-member-photo mad--ln-independent"><img src="/robohash/{% firstof user.get_short_name user.get_username|capfirst %}/?width=110&height=110" alt=""></a>
                                                                    <a href="/avatar/upload" class="btn btn-small btn-style-2">Edit Avatar</a>       
                                                                </figure>
                                                                    <!--================ End Of Team Member ================-->
                                                                </div>
                                                            </div>
                                                            {% endif %}
                
                                                            {% if user_profile %}
                                                            <br> 
                                                            <p><a href="{% url 'profiles:update' pk=user.id %}"class="btn warn">Update my Profile</a></p>
                                                            <p><a href="/accounts/password/change/"class="btn warn">Change Password</a></p>
                                                            <p><a href="{% url 'talks:talk_list' %}"class="btn warn">My Submitted Talks</a></p>
                                                            <p><a href="{% url 'talks:submit_talk' %}"class="btn warn">Submit a new Talk</a></p>
                                                            {% else %}
                                                            
                                                            {% endif %}
                                                        </ul>
                                                    </div>
                                            </div>
                                        </div>
                                </div>
                        </div>
                        <div class="col-sm-12 col-md-8"> 
                            <div class="panel panel-danger wow fadeInLeft">

                                <form action="{% url 'profiles:create_profile' %}" enctype='multipart/form-data' method='Post'>{% csrf_token %}
                                    
 
<!-- Trigger Modal Component --> 

                                    {{ form | crispy }}
                                    <br> 
                                    <div class="d-grid gap-5">
                                        <button class="btn primaryAction btn-big" style="background-position: 0px 59px;" type="submit" >Create Profile<i class="licon-chevron-right-circle"></i></button>
                                        
                                    </div> 
                                 </form>
                                    </div>
                
                            </div>
                        </div>
                
                    </div>
                    <!-- end .container -->
                </section>
              
            </main>
           
<!-- ========== ASIDE ========== -->
{% include '2022/aside.html' %}
<!-- ========== ASIDE ========== -->

          </div>
        </div>
      </div>
 

    <!-- end section.speakers -->
 
    
{% endblock %}

 

templates/profiles/login_details.html
{% extends "base2.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6">
<h2>Update your login details</h2>
<br>

<form action="" method=post>
    {% crispy form form.helper %}
          {% csrf_token %}
</form>

      </div>
    <div class="col-md-3">

    </div>
</div>

{% endblock %}

templates/profiles/password_change.html
{% extends "base2.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6">
<h2>Change your password</h2>
<br>

<form action="{% url 'profiles:password_change' user.pk %}" method=post>
    {% crispy form form.helper %}
          {% csrf_token %}
</form>

      </div>
    <div class="col-md-3">

    </div>
</div>

{% endblock %}

templates/profiles/success.html
{% extends "base2.html" %}

{% block content %}
<div class="row">
    <div class="col-md-2">

    </div>
	    <div class="col-md-8">
				<h2> Profile Update Successful! </h2>
				<br>
				<p>Your changes have been updated successfully.
				</p>

	   </div>
    <div class="col-md-2">

    </div>
</div>

{% endblock %}

templates/profiles/update.html
{% extends "base22.html" %}
{% load i18n static avatar_tags crispy_forms_tags %}
{% block meta_title %}{% if page %}{{ page.meta_title }}{% else %}{% trans "Profile | Pycon Ghana" %}{% endif %}{% endblock %}


{% block content %}

<!-- ========== HEADER ========== -->
{% include '2022/header.html' %}
<!-- ========== END HEADER ========== -->
 
    <!--================ Breadcrumb ================-->
    <div class="mad-breadcrumb">
        <div class="container">
          <h1 class="mad-page-title mad-title-with-line">Update {% firstof user.get_short_name user.get_username|capfirst %}'s Profile</h1>
          <nav class="mad-breadcrumb-path"><span><a href="/">Home</a></span>/<span><a href="/profile">Profile</a></span>/<span>Update Profile</span>
          </nav>
        </div>
      </div>
      <!--================ End of Breadcrumb ================-->

      <div class="mad-content">
        <div class="container">
          <div class="row mad-row-size-3">
            <main class="col-xl-9 col-lg-8">
                
                <section class="speakers" id="speakers">
                    <div class="container">
                    <div class="row">
                        <div class="col-sm-12 col-md-4"> 
                                <div class="panel panel-warning wow fadeInRight">
                                        <div class="panel-body">
                                           <div class="row">
                                                    <div class="col-md-10">
                                                        <ul> 
                                                            <div><b><small class="text-danger">LAST LOGIN</small></b></div>
                                                            <div><b><small>Date:</small></b>  {{ request.user.last_login.date }}</div>
                                                            <div><b><small>Time:</small></b>  {{ request.user.last_login.time }}</div>
                                                             
                                                            <br> 
                                                            <p><a href="/profile"class="btn warn"><i class="fa-solid fa-id-card" style="font-size:21px;"></i>&nbsp;&nbsp; Back to My Profile</a></p>
                                                            <p><a href="/accounts/password/change/"class="btn warn"><i class="fa-light fa-lock" style="font-size:21px;"></i>&nbsp;&nbsp; Change Password</a></p>
                                                            <p><a href="{% url 'talks:talk_list' %}"class="btn warn"><i class="fa-light fa-podium-star" style="font-size:21px;"></i>&nbsp;&nbsp; My Submitted Talks</a></p>
                                                            <p><a href="{% url 'talks:submit_talk' %}"class="btn warn"><i class="fa-light fa-podium" style="font-size:21px;"></i>&nbsp;&nbsp; Submit a new Talk</a></p>
                                                            
                                                            
                                                        </ul>
                                                    </div>
                                            </div>
                                        </div>
                                </div>
                        </div>
                        <div class="col-sm-12 col-md-8"> 
                            <div class="panel panel-danger wow fadeInLeft">
                                    <div class="panel-body"> 
                                    <div class="content-element"> 
                                    <div class="row">
                                        <div class="row text-center">
                                            <div class="col-md-6"> 
                                              <div class="content-element-5">
                                                {% if request.user|has_avatar %}                     
                                                <div data-isotope-layout="grid" data-isotope-filter="#portfolio-filter" class="mad-team  mad-grid--isotope">
                                                    <div class="mad-grid-sizer"></div>
                                                    <div class="mad-grid-item mad-category-programming">
                                                        <!--================ Team Member ================--> 
                                                        <figure class="mad-team-member">
                                                        {% avatar user 110 class="img-circle img-responsive" id="user_avatar" %}
                                                        <a href="/avatar/change" class="btn btn-small btn-style-2">Edit Avatar</a> 

                                                        <a href="/avatar/delete" class="btn btn-small btn-style-3">Delete an Avatar</a> 
                                                        </figure>
                                                        <!--================ End Of Team Member ================-->
                                                    </div> 
                                                </div>      
                                                {% else %} 
                                                <div data-isotope-layout="grid" data-isotope-filter="#portfolio-filter" class="mad-team  mad-grid--isotope">
                                                    <div class="mad-grid-sizer"></div>
                                                    <div class="mad-grid-item mad-category-programming">
                                                        <!--================ Team Member ================-->
                                                        <figure class="mad-team-member">
                                                        <a class="mad-team-member-photo mad--ln-independent"><img src="/robohash/{% firstof user.get_short_name user.get_username|capfirst %}/?width=110&height=110" alt=""></a>
                                                        <a href="/avatar/upload" class="btn btn-small btn-style-2">Edit Avatar</a> 
                                                    </figure>
                                                        <!--================ End Of Team Member ================-->
                                                    </div>
                                                    
                                                </div>
                                                {% endif %}
                                              </div>
                                            </div>  
                                           </div>  
                                           <div class="col-sm-12 col-md-8"> 
                                            <div class="panel panel-danger wow fadeInLeft">
                                                <p class="mad-sub-title">Update your details</p>
                                                <form action="{% url 'profiles:create_profile' %}" enctype='multipart/form-data' method='Post'>{% csrf_token %}
                                                    
                 
                <!-- Trigger Modal Component --> 
                
                                                    {{ form | crispy }}
                                                    <br> 
                                                    <div class="d-grid gap-5">
                                                        <button class="btn primaryAction btn-big" style="background-position: 0px 59px;" type="submit" >Update Profile<i class="licon-chevron-right-circle"></i></button>
                                                        
                                                    </div> 
                                                 </form>
                                                    </div>
                                
                                            </div>
                                        </div> 
                                      </div>
                           
                                    </div>
                
                            </div>
                        </div>
                
                    </div>
                    <!-- end .container -->
                </section>
              
            </main>
            
<!-- ========== ASIDE ========== -->
{% include '2022/aside.html' %}
<!-- ========== ASIDE ========== -->

          </div>
        </div>
      </div>
 

    <!-- end section.speakers -->



{% endblock %}

 